#!/usr/bin/env python3
"""Reproduce the optimization plots: Python 3 + NumPy, no plotting packages.

Run from any working directory. All output locations derive from this file.
The PGFPlots files embed coordinates, so compiling them does not run Python.
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path
import platform

import numpy as np


HERE = Path(__file__).resolve().parent
FIGURES = HERE.parent / "figures"
REVIEW = HERE / "optimization-review.md"
RAW_X = np.array([.2, .7, 1.1, 1.6, 2.1, 2.5, 3.1, 3.6, 4., 4.4,
                  4.9, 5.3, 5.7, 6.2, 6.7, 7.1, 7.6, 8.1, 8.7, 9.4])
POSITIVE_X = np.array([3.6, 4.4, 5.3, 6.2, 6.7, 7.6, 8.1, 8.7, 9.4])
Y = np.isin(RAW_X, POSITIVE_X).astype(float)
X = np.column_stack((np.ones(RAW_X.size), (RAW_X - 5.) / 2.))
N = Y.size
ITERATIONS = 100


def sigmoid(z):
    z = np.asarray(z, dtype=float)
    p = np.empty_like(z)
    mask = z >= 0
    p[mask] = 1. / (1. + np.exp(-z[mask]))
    ez = np.exp(z[~mask])
    p[~mask] = ez / (1. + ez)
    return p


def loss(theta, design=X, labels=Y):
    # log(1+exp(-z)) for y=1, log(1+exp(z)) for y=0; no cancellation.
    return float(np.mean(np.logaddexp(0., (1. - 2. * labels) * (design @ theta))))


def gradient(theta, design=X, labels=Y):
    return design.T @ (sigmoid(design @ theta) - labels) / labels.size


def hessian(theta, design=X):
    p = sigmoid(design @ theta)
    return design.T @ ((p * (1. - p))[:, None] * design) / design.shape[0]


def newton_reference():
    theta = np.zeros(2)
    steps = 0
    for _ in range(50):
        g = gradient(theta)
        if np.linalg.norm(g, ord=np.inf) < 1e-13:
            break
        step = np.linalg.solve(hessian(theta), g)
        rate = 1.
        objective = loss(theta)
        while loss(theta - rate * step) > objective - 1e-4 * rate * float(g @ step):
            rate *= .5
            if rate < 1e-12:
                raise ArithmeticError("Newton line search failed")
        theta -= rate * step
        steps += 1
    assert np.linalg.norm(gradient(theta), ord=np.inf) < 1e-12
    return theta, steps


def trajectory(eta):
    theta = np.zeros(2)
    rows = []
    for iteration in range(ITERATIONS + 1):
        rows.append({"iteration": iteration, "b": float(theta[0]),
                     "w": float(theta[1]), "loss": loss(theta),
                     "gradient_norm": float(np.linalg.norm(gradient(theta)))})
        if iteration < ITERATIONS:
            theta -= eta * gradient(theta)
    return rows


def write_csv(name, header, rows):
    with (HERE / name).open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(header)
        writer.writerows(rows)


def coords(xs, ys):
    return " ".join(f"({float(x):.12g},{float(y):.12g})" for x, y in zip(xs, ys))


def figure(axis_options, plots, description):
    return ("% " + description + "\n"
            "% Generated by examples/generate_optimization.py; constructed teaching data.\n"
            r"\begingroup" + "\n"
            r"\definecolor{blueplot}{HTML}{4E79A7}" + "\n"
            r"\definecolor{redplot}{HTML}{D95F59}" + "\n"
            r"\definecolor{greenplot}{HTML}{248377}" + "\n"
            r"\begin{tikzpicture}" + "\n"
            r"\begin{axis}[" + "\n"
            r"width=\linewidth,height=4.6cm,font=\scriptsize," + "\n"
            r"tick label style={font=\scriptsize},label style={font=\scriptsize}," + "\n"
            r"axis line style={black!45},tick style={black!45}," + "\n"
            r"grid=major,grid style={black!10},scaled ticks=false,clip=true," + "\n"
            r"legend style={font=\scriptsize,draw=none,fill=white,fill opacity=.94," + "\n"
            r"text opacity=1,legend cell align=left,inner sep=2pt,row sep=1pt}," + "\n"
            + axis_options + "\n]\n" + "\n".join(plots) + "\n"
            r"\end{axis}" + "\n" + r"\end{tikzpicture}" + "\n" + r"\endgroup" + "\n")


def addplot(options, points, legend=None):
    text = r"\addplot[" + options + "] coordinates {" + points + "};"
    if legend is not None:
        text += "\n" + r"\addlegendentry{" + legend + "}"
    return text


def main():
    HERE.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    REVIEW.parent.mkdir(parents=True, exist_ok=True)
    assert N == 20 and int(Y.sum()) == 9 and int((1 - Y).sum()) == 11
    singular = np.linalg.svd(X, compute_uv=False)
    L = float(singular[0] ** 2 / (4 * N))
    theta_star, newton_steps = newton_reference()
    jstar = loss(theta_star)
    settings = [("slow", .1, "blueplot,dashed"),
                ("safe", 1., "greenplot"),
                ("aggressive", 10., "redplot")]
    runs = {}
    all_rows = []
    for name, multiplier, _ in settings:
        eta = multiplier / L
        rows = trajectory(eta)
        losses = np.array([row["loss"] for row in rows])
        theta_final = np.array([rows[-1]["b"], rows[-1]["w"]])
        increases = int(np.count_nonzero(np.diff(losses) > 1e-12))
        assert np.isfinite(losses).all()
        if name in ("slow", "safe"):
            assert increases == 0
        else:
            assert increases > 0 and losses[1] > losses[0] + .1
        runs[name] = {"eta_multiplier": multiplier, "eta": eta, "iterations": ITERATIONS,
                      "initial_loss": rows[0]["loss"], "first_loss": rows[1]["loss"],
                      "final_loss": rows[-1]["loss"], "final_theta": theta_final.tolist(),
                      "final_probabilities": sigmoid(X @ theta_final).tolist(),
                      "final_gradient_norm": rows[-1]["gradient_norm"],
                      "loss_increases_gt_1e-12": increases, "trajectory": rows}
        all_rows.extend([name, multiplier, eta, row["iteration"], row["b"], row["w"],
                         row["loss"], row["gradient_norm"]] for row in rows)
    assert abs(runs["safe"]["final_loss"] - jstar) < 1e-12
    assert np.linalg.norm(np.array(runs["safe"]["final_theta"]) - theta_star) < 1e-9

    epsilon = 1e-5
    max_gradient_error = max_hessian_error = 0.
    for theta in (np.zeros(2), np.array([-.7, .8]), np.array([1.2, -2.1]), theta_star):
        basis = np.eye(2) * epsilon
        fd_gradient = np.array([(loss(theta + e) - loss(theta - e)) / (2 * epsilon) for e in basis])
        fd_hessian = np.column_stack([(gradient(theta + e) - gradient(theta - e)) / (2 * epsilon) for e in basis])
        max_gradient_error = max(max_gradient_error, float(np.max(np.abs(fd_gradient - gradient(theta)))))
        max_hessian_error = max(max_hessian_error, float(np.max(np.abs(fd_hessian - hessian(theta)))))
    assert max_gradient_error < 1e-8 and max_hessian_error < 1e-8
    # Extreme scores remain finite without clipping probabilities.
    extreme_loss = float(np.mean(np.logaddexp(0., np.array([-1000., 1000.]))))
    assert math.isfinite(extreme_loss) and np.isfinite(sigmoid([-1000., 1000.])).all()

    toy_x = np.column_stack((np.ones(3), [-1., 0., 1.]))
    toy_y = np.array([0., 0., 1.])
    toy_gradient = gradient(np.zeros(2), toy_x, toy_y)
    toy_theta = -toy_gradient
    toy_loss = loss(toy_theta, toy_x, toy_y)
    assert np.allclose(toy_theta, [-1 / 6, 1 / 3], rtol=0., atol=1e-15)
    assert abs(toy_loss - .56688037) < 5e-9

    checks = {"finite_difference_step": epsilon, "finite_difference_points": 4,
              "max_gradient_absolute_error": max_gradient_error,
              "max_hessian_absolute_error": max_hessian_error,
              "finite_difference_tolerance": 1e-8,
              "monotonicity_tolerance": 1e-12, "extreme_score_loss": extreme_loss}
    summary = {"data_kind": "constructed teaching observations", "n": N,
               "positive_count": int(Y.sum()), "negative_count": int((1 - Y).sum()),
               "feature": "(x_raw - 5) / 2", "loss": "mean binary cross-entropy; no regularization",
               "initial_theta": [0., 0.], "L_bound": L, "spectral_norm_X": float(singular[0]),
               "raw_x": RAW_X.tolist(), "labels": Y.astype(int).tolist(),
               "reference": {"method": "Newton with Armijo backtracking", "steps": newton_steps,
                             "theta": theta_star.tolist(), "loss": jstar,
                             "gradient_inf_norm": float(np.linalg.norm(gradient(theta_star), ord=np.inf)),
                             "hessian_eigenvalues": np.linalg.eigvalsh(hessian(theta_star)).tolist(),
                             "probabilities": sigmoid(X @ theta_star).tolist()},
               "runs": runs, "checks": checks,
               "one_step": {"x": [-1, 0, 1], "y": [0, 0, 1], "eta": 1.,
                            "gradient_at_zero": toy_gradient.tolist(), "theta_after": toy_theta.tolist(),
                            "loss_before": math.log(2.), "loss_after": toy_loss,
                            "probabilities_after": sigmoid(toy_x @ toy_theta).tolist()},
               "dependencies": {"python": platform.python_version(), "numpy": np.__version__}}
    (HERE / "optimization-results.json").write_text(json.dumps(summary, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    write_csv("optimization-runs.csv", ["run", "eta_times_L", "eta", "iteration", "b", "w", "mean_bce", "gradient_norm"], all_rows)
    write_csv("optimization-data.csv", ["x_raw", "x_standardized", "y", "p_reference", "p_safe_100"],
              zip(RAW_X, X[:, 1], Y.astype(int), summary["reference"]["probabilities"], runs["safe"]["final_probabilities"]))

    loss_plots = []
    for name, multiplier, style in settings:
        rows = runs[name]["trajectory"]
        label = {"slow": r"$\eta=0.1/\overline L$", "safe": r"$\eta=1/\overline L$", "aggressive": r"$\eta=10/\overline L$"}[name]
        loss_plots.append(addplot(style + ",thick,no marks", coords([r["iteration"] for r in rows], [r["loss"] for r in rows]), label))
    loss_plots.append(addplot("black!65,densely dashed,no marks", coords([0, ITERATIONS], [jstar, jstar]), r"$J^\star$"))
    (FIGURES / "opt-loss.tex").write_text(figure(
        r"xmin=0,xmax=100,ymin=.38,ymax=1.26,xtick={0,20,40,60,80,100}," + "\n"
        r"ytick={.4,.6,.8,1,1.2},xlabel={Iteration $t$},ylabel={Mean BCE $J$}," + "\n"
        r"legend pos=north east,legend columns=2",
        loss_plots, "Actual full-batch gradient descent loss, 100 updates per learning rate."), encoding="utf-8")

    raw_grid = np.linspace(0., 10., 241)
    grid_design = np.column_stack((np.ones(raw_grid.size), (raw_grid - 5) / 2))
    theta_safe = np.array(runs["safe"]["final_theta"])
    p_grid = sigmoid(grid_design @ theta_safe)
    write_csv("optimization-fit-grid.csv", ["x_raw", "p_safe_100"], zip(raw_grid, p_grid))
    fit_plots = [
        addplot("greenplot,thick,no marks", coords(raw_grid, p_grid), "GD, 100 iterations"),
        addplot("blueplot,only marks,mark=o,mark size=2pt,thick", coords(RAW_X[Y == 0], Y[Y == 0]), "$y=0$"),
        addplot("redplot,only marks,mark=triangle*,mark size=2.6pt", coords(RAW_X[Y == 1], Y[Y == 1]), "$y=1$")]
    (FIGURES / "opt-fit.tex").write_text(figure(
        r"xmin=0,xmax=10,ymin=-.06,ymax=1.06,xtick={0,2,4,6,8,10},ytick={0,.5,1}," + "\n"
        r"xlabel={Input $x_{\mathrm{raw}}$},ylabel={Fitted probability},legend columns=3,legend style={at={(.5,1.04)},anchor=south}",
        fit_plots, "Same 20 observations; fitted sigmoid uses eta=1/Lbar after 100 updates."), encoding="utf-8")

    # Compute exact level curves numerically by ray-wise root finding about the
    # strict convex minimum. PGFPlots receives native line coordinates only.
    contour_levels = [.42, .45, .5, .6, .8]
    contour_plots = []
    contour_rows = []
    max_contour_error = 0.
    for i, level in enumerate(contour_levels):
        contour = []
        for angle in np.linspace(0., 2 * math.pi, 145):
            direction = np.array([math.cos(angle), math.sin(angle)])
            lo, hi = 0., 1.
            while loss(theta_star + hi * direction) < level:
                hi *= 2.
                assert hi < 1e4
            for _ in range(48):
                mid = (lo + hi) / 2.
                if loss(theta_star + mid * direction) < level:
                    lo = mid
                else:
                    hi = mid
            point = theta_star + .5 * (lo + hi) * direction
            contour.append(point)
            actual = loss(point)
            max_contour_error = max(max_contour_error, abs(actual - level))
            contour_rows.append([level, angle, *point, actual])
        pts = np.array(contour)
        contour_plots.append(addplot(f"black!{25 + 8 * i},thin,no marks,forget plot", coords(pts[:, 0], pts[:, 1])))
    assert max_contour_error < 1e-10
    checks["max_contour_level_absolute_error"] = max_contour_error
    rows = runs["safe"]["trajectory"][:11]
    contour_plots.extend([
        addplot("greenplot,thick,mark=*,mark size=1.25pt", coords([r["b"] for r in rows], [r["w"] for r in rows]), r"$\eta=1/\overline L$: first 10 steps"),
        addplot("black,only marks,mark=star,mark size=2.5pt", coords([theta_star[0]], [theta_star[1]]), "Minimum")])
    (FIGURES / "opt-contour.tex").write_text(figure(
        r"xmin=-2,xmax=2,ymin=-.4,ymax=4.2,xtick={-2,-1,0,1,2},ytick={0,1,2,3,4}," + "\n"
        r"xlabel={Intercept $b$},ylabel={Slope $w$},legend pos=north east",
        contour_plots, "Mean BCE contours .42,.45,.50,.60,.80; first ten safe gradient descent steps."), encoding="utf-8")
    write_csv("optimization-contours.csv", ["target_mean_bce", "angle", "b", "w", "actual_mean_bce"], contour_rows)
    (HERE / "optimization-results.json").write_text(json.dumps(summary, indent=2, allow_nan=False) + "\n", encoding="utf-8")

    table_rows = "\n".join(
        f"| {name} | {runs[name]['eta']:.12f} | {runs[name]['final_loss']:.12f} | "
        f"{runs[name]['final_theta'][0]:.12f} | {runs[name]['final_theta'][1]:.12f} | "
        f"{runs[name]['loss_increases_gt_1e-12']} |" for name, _, _ in settings)
    probability_rows = "\n".join(f"| {x:.1f} | {int(y)} | {p:.10f} |" for x, y, p in zip(RAW_X, Y, summary["reference"]["probabilities"]))
    report = f"""# Optimization figure numerical review

Generated by `examples/generate_optimization.py` in this lecture package.
Run with Python 3 and NumPy; verified Python {platform.python_version()}, NumPy {np.__version__}.
No scipy, matplotlib, external data, random sampling, or TeX shell escape is used.
The script reproduces every TeX, CSV, JSON, and review file from any working directory.

## Definition and sample

There are **20** fixed constructed observations: **9 positive, 11 negative**.
Use z=(x_raw−5)/2 and design rows (1,z). Parameters are (b,w) in these transformed coordinates.
The objective is mean binary cross-entropy, with no regularizer. All three runs start at (0,0)
and execute exactly 100 full-batch updates; each saved trajectory contains 101 points including t=0.
The figure shows actual computed BCE, never a manufactured convergence curve or loss gap.

The spectral norm of X is {singular[0]:.15f}, and the global curvature bound L̄=||X||₂²/(4n)={L:.15f}.
Initial loss is log(2)={math.log(2):.15f}.
Newton with Armijo backtracking takes {newton_steps} steps to
(b*,w*)=({theta_star[0]:.15f},{theta_star[1]:.15f}), with J*={jstar:.15f}.
The reference gradient infinity norm is {summary['reference']['gradient_inf_norm']:.3e};
Hessian eigenvalues are {summary['reference']['hessian_eigenvalues']}.
The mixed labels overlap in input order, so this is a nonseparable example with a finite minimum.

| Run | η | J at t=100 | b at t=100 | w at t=100 | Loss increases >1e−12 |
|---|---:|---:|---:|---:|---:|
{table_rows}

The aggressive run's first update raises loss to {runs['aggressive']['first_loss']:.15f}.
Calling it nonmonotone or oscillatory is accurate; the finite 100-step experiment does not establish divergence to infinity.
The safe final parameter distance from Newton is {np.linalg.norm(theta_safe-theta_star):.3e};
its loss gap is {runs['safe']['final_loss']-jstar:.3e}.

## Verification

- Stable sigmoid evaluates only the appropriate exponential branch; BCE uses `logaddexp` of the signed score.
- Scores ±1000 produce finite BCE and probabilities without probability clipping.
- Central differences at 4 parameter vectors, step {epsilon:g}: max gradient error {max_gradient_error:.3e}, max Hessian error {max_hessian_error:.3e}; both tolerances 1e−8.
- Slow and safe losses are nonincreasing up to tolerance 1e−12. The aggressive run has {runs['aggressive']['loss_increases_gt_1e-12']} increases.
- Safe final loss agrees with Newton within 1e−12 and final parameters within Euclidean tolerance 1e−9.
- All contour points solve the actual objective-level equation; maximum residual {max_contour_error:.3e}, tolerance 1e−10.
- One-step exercise x=(−1,0,1), y=(0,0,1), η=1: gradient at zero=(1/6,−1/3), new θ=(−1/6,1/3); mean BCE={toy_loss:.15f}, agreeing with .56688037 within 5e−9.

## Figure captions and rendering contract

- **opt-loss.tex:** Mean BCE over 100 gradient descent updates on the same 20 observations. The blue, green, and red curves use η=0.1/L̄, 1/L̄, and 10/L̄. The dashed gray line is the Newton reference minimum. A large step repeatedly increases the objective.
- **opt-fit.tex:** The sigmoid after 100 updates with η=1/L̄, over the same 20 binary observations. The model is fitted in z=(x_raw−5)/2 coordinates; the horizontal axis shows raw x.
- **opt-contour.tex:** Mean BCE level curves at .42, .45, .50, .60, and .80 in the (b,w) plane, with the first ten η=1/L̄ steps and the Newton minimum.

All plots are native PGFPlots with inline numerical coordinates, width=\\linewidth, height=4.6cm,
and \\scriptsize text. Colors: blue #4E79A7, red #D95F59, green #248377.
Final probabilities for every run and every iteration's parameters/loss are saved in `optimization-results.json`;
CSV files also save the observations, all 303 trajectory rows, 241 fitted-curve points, and 725 contour points.

## Reference fitted probabilities

| Raw x | y | p at reference minimum |
|---|---:|---:|
{probability_rows}
"""
    REVIEW.write_text(report, encoding="utf-8")
    print(json.dumps({"status": "PASS", "L_bound": L, "reference": summary["reference"],
                      "runs": {name: {k: v for k, v in run.items() if k not in ("trajectory", "final_probabilities")} for name, run in runs.items()},
                      "one_step": summary["one_step"], "checks": checks,
                      "figures": ["opt-loss.tex", "opt-fit.tex", "opt-contour.tex"]}, indent=2))


if __name__ == "__main__":
    main()
